### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by demetrio812** [henrychavez/nativescript-bottom-navigation#9]
Hello,
I've just tested the app on an iPhone X and the bottom safe area is not considered:

<img width="351" alt="screenshot 2018-02-21 17 52 59" src="https://user-images.githubusercontent.com/385644/36496465-34046626-1730-11e8-9f3d-ef921c5c02a5.png">

I don't know if the version 1.1.1 of the original MiniTabBar fixed this, is there a specific reason why you forked it?

Thanks,
Dem

**Comment by henrychavez** [comment]
Hi,
Yes, I forked the project to be able to use it with Nativescript and perform some modifications and don't depend of the original project to be updated.

Thanks for report this issue, I think this will be fixed if I just update my project MiniTabBar so the only think that you need to do is remove the plugin and reinstall. 

Probably this will be fixed tomorrow because today I'm really busy with some other stuffs.

I let you know when it's ready! 😄

**Comment by henrychavez** [comment]
@demetrio812 The new version 1.2.0 solve this problem 😄  Just update and enjoy!

**Comment by demetrio812** [comment]
Hello, thanks for that, unfortunately, this is what I see now:

![simulator screen shot - iphone x - 2018-02-28 at 16 57 20](https://user-images.githubusercontent.com/385644/36802177-278d4c7e-1cac-11e8-8de0-45b11e8e4b7f.png)

Let me know if you need me to do some other test

Cheers,
Dem

**Comment by henrychavez** [comment]
Yes you need to delete your platforms/ios folder to get the lates version of the ios library

**Comment by demetrio812** [comment]
I did it, I also tried with the real iPhone X, it looks like there is a new version because the icons are up now, but not the text...

Will try again and let you know...

Thanks,
Dem

**Comment by henrychavez** [comment]
Try removing the platforms/ios and running this `pod repo update` to get the latest version of the MiniTabBar

**Comment by demetrio812** [comment]
It worked! I think the `pod repo update` made the trick! Thanks for the support!
